### ISSUE TITLE
Make target with Calico not working.

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/sig-windows-dev-tools#242]
Bringing up the cluster with Calico as CNI is failing with the issue:

```
pod/whoami-windows-6f7964957-mhk75 condition met
pod/whoami-windows-6f7964957-s5vrq condition met
cni: calico
curl: (28) Failed to connect to whoami-windows port 80 after 129859 ms: Couldn't connect to server
command terminated with exit code 28
make: *** [3-smoke-test] Error 28
```

Steps that were followed:
1) Check if all pods are in running state: status: running
2) Curl the Windows pod ip: Didn't work
3) Tried to exec into the windows pod: couldn't proceed as little off with windows 

Observation:
Looks like calico config files are commented out [here](https://github.com/kubernetes-sigs/sig-windows-dev-tools/blob/master/Vagrantfile#L94-L95)

**Comment by geetikabatra** [comment]
cc: @knabben

**Comment by jayunit100** [comment]
yup were seeing that calico somehow isn't networking across nodes

- windows -> windows networking works on calico
- linux -> linux chi works locally 


so something between VMs isn't working

**Comment by bishtsaurabh5** [comment]
Some of my observations:
1) I did port-forwarding for the windows pods as well as service in the linux VM and was able to do curl so that means that connections between the node is indeed possible
I tried checking the calico pod logs but did not find anything weird there. @jayunit100 / @knabben any pointers as to where can I look ?
